baseURL = 'https://piefayth.github.io/blog/'
languageCode = 'en-us'
title = "Piefayth's Blog"
theme = "hugo-blog-awesome"

[params.author]
    avatar = "charlie.png"
    intro = "Piefayth"
    description = "Backend wizard. Decentralization enthusiast."

[[params.socialIcons]]
name = "github"
url = "https://github.com/piefayth"

[[params.socialIcons]]
name = "discord"
url = "https://discord.com/users/piefayth"

[markup]
    [markup.highlight]
        style = 'catppuccin-mocha'