baseURL = 'https://piefayth.github.io/blog/'
languageCode = 'en-us'
title = "Piefayth's Blog"
theme = "hugo-blog-awesome"

[params.author]
    avatar = "charlie.png"

[[params.socialIcons]]
name = "github"
url = "https://github.com/piefayth"

[params]
    toc = true